'Solution'
mate-academy/py-docker-weather-api pull request #34
Opened 2022-09-07 12:45 UTC by LaskoA

Please check my solution (image file is pretty big so please advice how to fix it). Thank you.

2022-09-07 13:38 UTC, LaskoA commented
Managed to decrease image size from 1GB to 400MB - please check it with next command:
"docker pull laskoa/docker-weather-api-slim"

Thank you.

2022-09-07 16:23 UTC, LaskoA commented
Now image is "only" 341Mb, please use next command:
"docker pull laskoa/docker-weather-api-slim-v3"

Thanks in advance.

2022-09-08 07:45 UTC, DmytroSvirsa requested changes

2022-09-08 07:45 UTC, DmytroSvirsa commented on .env
> +API_KEY=7c508243647f4c4b971122001220609
that is your secret API_KEY, never push stuff like this,

2022-09-08 08:17 UTC, DmytroSvirsa requested changes

2022-09-08 08:17 UTC, DmytroSvirsa commented on Dockerfile
> +CMD ["python", "manage.py", "runserver"]
error python: can't open file '/app/manage.py': [Errno 2] No such file or directory

2022-09-08 08:17 UTC, DmytroSvirsa commented on Dockerfile
> +    && pip install psycopg2
you can add it to requirements.txt

2022-09-08 09:03 UTC, LaskoA commented
Please check now after fixes, use command "docker pull laskoa/docker-weather-api" (old images were deleted from Docker).

P.S.: If you don`t mind I would leave next string in dockerfile (not in requirements.txt):
    RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

The thing is slim-image did not work without it so I would like to keep it seperately for the future as a reminder :)

Thank you.

2022-09-08 12:40 UTC, DmytroSvirsa approved these changes
Yep, well done!

2022-09-08 12:44 UTC, closed without merging