Develop
mate-academy/py-docker-weather-api pull request #347
Opened 2023-12-06 20:46 UTC by vshvanska

2023-12-07 14:35 UTC, Shatrovskyi approved these changes
Well done!

2023-12-13 11:39 UTC, LiudmylaKulinchenko requested changes
`You must modify this line with correct command to pull your image: COMMAND=docker pull <YOUR_DOCKER_ID/YOUR_IMAGE_NAME>.` -- fix that in your readme

2023-12-13 11:39 UTC, LiudmylaKulinchenko commented on app/main.py
> +                                    "aqi": "no"})
consider to create dict with params outside of method to make it more readable

2023-12-19 18:29 UTC, wQuelS requested changes

2023-12-19 18:29 UTC, wQuelS commented on .dockerignor
> +venv
better to add `venv/` as a folder

2023-12-19 18:29 UTC, wQuelS commented on Dockerfile
> +FROM python:3.11.4
it is almost always better to use light version to not install "full python". For example `FROM python:3.10-slim`  - but with needed version

2023-12-19 18:29 UTC, wQuelS commented on app/main.py
> +from dotenv import load_dotenv
what about spaces between different group of imports?

2023-12-21 17:06 UTC, Y-Havryliv approved these changes
GJ!

2023-12-21 17:06 UTC, Y-Havryliv commented on .dockerignor
it should be named `.dockerignore`

2025-01-27 18:02 UTC, closed without merging