solution
mate-academy/py-docker-weather-api pull request #392
Opened 2024-01-24 20:01 UTC by VladyslavOladko

Link on Docker Hub repository: https://hub.docker.com/r/vladyslavoladko/docker-weather-api

2024-01-25 09:26 UTC, ArsenPidhoretskyi requested changes

2024-01-25 09:26 UTC, ArsenPidhoretskyi commented on .dockerignore
> +.venv
Add empty line

2024-01-25 09:26 UTC, ArsenPidhoretskyi commented on app/main.py
> +    response = requests.get(url).json()
Okey, but in case response status code is 4xx or 5xx?

2024-01-28 11:21 UTC, VladyslavOladko commented on app/main.py
> +    response = requests.get(url).json()
In this case I have 200 status code, or maybe I didnt understand ur question
![image](https://github.com/mate-academy/py-docker-weather-api/assets/117306506/62d75f94-29fd-4494-b085-ea3b693c2e4b)

2024-01-28 11:24 UTC, VladyslavOladko commented on app/main.py
> +    response = requests.get(url).json()
Or I can implement if-else structure that will remebmer to set environment variable API_KEY in terminal

2024-01-28 15:25 UTC, vsmutok requested changes

2024-01-28 15:25 UTC, vsmutok commented on app/main.py
> +        )
I think it's better to check if  API_KEY  in your env variables use `os.getenv("API_KEY")`

2024-01-28 15:25 UTC, vsmutok commented on app/main.py
> +    try:
```suggestion
    if not os.getenv("API_KEY"):
        raise TypeError(
            "Set your environment variable API_KEY "
            "in terminal and run this script again"
        )
```

2024-01-31 12:02 UTC, ArsenPidhoretskyi requested changes

2024-01-31 12:02 UTC, ArsenPidhoretskyi commented on app/main.py
> +    response_json = requests.get(url).json()
But if response status code will not be successful?

2024-03-14 18:55 UTC, ArsenPidhoretskyi requested changes

2024-03-14 18:55 UTC, ArsenPidhoretskyi commented on app/main.py
> +    response_json = requests.get(url).json()
```suggestion
    response = requests.get(url)
    
    if response.status_code != 200:
        raise ValueError("Invalid status code")

    response_json = requests.get(url).json()
```
== really can throw an error?

2024-05-12 16:57 UTC, vsmutok approved these changes
Well Done 👍

2025-09-25 19:11 UTC, closed without merging