Solution
mate-academy/py-docker-weather-api pull request #682
Opened 2024-12-23 06:58 UTC by molodsh1y1

![Screenshot 2024-12-23 085121](https://github.com/user-attachments/assets/1c0e674d-d871-4d5e-94c4-0aecab0e90ee)

2024-12-24 10:00 UTC, Arsen-hrynevych requested changes
Mostly correct. Thanks

2024-12-24 10:00 UTC, Arsen-hrynevych commented on .dockerignore
> +**/**__pycache__/
Please include more files

2024-12-24 10:00 UTC, Arsen-hrynevych commented on Dockerfile
> +CMD ["python", "app/main.py"]
```
`# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

ARG PYTHON_VERSION=3.12
FROM python:${PYTHON_VERSION}-slim as base

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Create a non-privileged user that the app will run under.
# See https://docs.docker.com/go/dockerfile-user-best-practices/
ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.cache/pip to speed up subsequent builds.
# Leverage a bind mount to requirements.txt to avoid having to copy them into
# into this layer.
RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    python -m pip install -r requirements.txt

# Switch to the non-privileged user to run the application.
USER appuser

# Copy the source code into the container.
COPY . .

# Run the application.
CMD python app/main.py
`
```

2024-12-24 10:00 UTC, Arsen-hrynevych commented on app/main.py
> +FILTERING = "Paris"
make it dynamic also

2024-12-24 10:00 UTC, Arsen-hrynevych commented on app/main.py
> +from dotenv import load_dotenv
Imports should be grouped and separated by a blank line according to standard library, external libraries, and custom imports. This practice enhances both code readability and maintainability. 
Read more about topic [here](https://peps.python.org/pep-0008/#imports)

2024-12-24 10:00 UTC, Arsen-hrynevych commented on app/main.py
> +API_KEY = os.getenv("API_KEY")
os.getenv doesn't raise a KeyError exception if the key is not provided. You can use os.environ and remove the if statement.

2024-12-24 10:00 UTC, Arsen-hrynevych commented on app/main.py
> +def print_weather_data(data: dict) -> None:
Please add short docstings

2025-01-20 15:11 UTC, AnyoneClown approved these changes
LGTM

2026-01-08 21:35 UTC, closed without merging